## DataProcessing_Columns
- 아웃라이어 제거?, 컬럼별 아웃라이어 제거, 제거 시, 데이터 수? 얼마나 데이터가 제거되는지
- 이상한 부분? Ex) 이동거리 0인데 승률이 높은 경우.
- 데이터 스케일링

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl
import os
import matplotlib.dates as mdates

pd.set_option('display.max_columns',None)
# pd.set_option('display.max_rows',None)

In [25]:
df = pd.read_csv("Downloads/pubg-finish-placement-prediction/train_V2.csv")

In [26]:
df = df[['matchId','matchType','Id','groupId','assists','killPlace','kills','matchDuration', 'boosts' ,'damageDealt', 'heals',  'killStreaks', 'longestKill', 'walkDistance','winPlacePerc']]

# killplace

In [27]:
# df[(df['kills'] ==0) & (df['killPlace'] >40)]

In [28]:
df_1 = df[(df['matchId']== '2001300d4f5787') & (df['kills']<3) & (df['killPlace']<50) & (df['winPlacePerc']<0.1)] 
df_1.sort_values('killPlace',ascending=False)

,matchId,matchType,Id,groupId,assists,killPlace,kills,matchDuration,boosts,damageDealt,heals,killStreaks,longestKill,walkDistance,winPlacePerc
1412777,2001300d4f5787,duo-fpp,5d5848317c43e7,58bc4104935623,0,42,1,1414,0,52.70,0,1,9.749,34.92,0.0000
2967745,2001300d4f5787,duo-fpp,c696bab95b015e,de180c28e7c199,0,23,2,1414,0,76.78,0,2,14.960,20.68,0.0851

In [29]:
df[(df['matchId']== '2001300d4f5787') & (df['groupId'] == 'de180c28e7c199')]

,matchId,matchType,Id,groupId,assists,killPlace,kills,matchDuration,boosts,damageDealt,heals,killStreaks,longestKill,walkDistance,winPlacePerc
1083506,2001300d4f5787,duo-fpp,0cfd797108cab8,de180c28e7c199,0,83,0,1414,0,24.48,0,0,0.00,66.78,0.0851
2967745,2001300d4f5787,duo-fpp,c696bab95b015e,de180c28e7c199,0,23,2,1414,0,76.78,0,2,14.96,20.68,0.0851

In [30]:
df[(df['matchId']== '2001300d4f5787') & (df['groupId'] == '58bc4104935623')]

,matchId,matchType,Id,groupId,assists,killPlace,kills,matchDuration,boosts,damageDealt,heals,killStreaks,longestKill,walkDistance,winPlacePerc
1412777,2001300d4f5787,duo-fpp,5d5848317c43e7,58bc4104935623,0,42,1,1414,0,52.7,0,1,9.749,34.92,0.0
1910927,2001300d4f5787,duo-fpp,a20c6238c5bfde,58bc4104935623,0,94,0,1414,0,0.0,0,0,0.000,0.00,0.0
2238391,2001300d4f5787,duo-fpp,20151d4d3c5c33,58bc4104935623,0,91,0,1414,0,0.0,0,0,0.000,0.00,0.0
3506230,2001300d4f5787,duo-fpp,7c20ae10270dc3,58bc4104935623,0,93,0,1414,0,0.0,0,0,0.000,0.00,0.0
4120602,2001300d4f5787,duo-fpp,64b6cdc85fcd02,58bc4104935623,1,95,0,1414,0,47.3,0,0,0.000,12.89,0.0
4133549,2001300d4f5787,duo-fpp,0263a26877549c,58bc4104935623,0,90,0,1414,0,0.0,0,0,0.000,0.00,0.0
4446958,2001300d4f5787,duo-fpp,837349af7e8a35,58bc4104935623,0,92,0,1414,0,0.0,0,0,0.000,0.00,0.0

In [31]:
df_1.groupby('groupId').mean()

,assists,killPlace,kills,matchDuration,boosts,damageDealt,heals,killStreaks,longestKill,walkDistance,winPlacePerc
groupId,,,,,,,,,,,
58bc4104935623,0.0,42.0,1.0,1414.0,0.0,52.70,0.0,1.0,9.749,34.92,0.0000
de180c28e7c199,0.0,23.0,2.0,1414.0,0.0,76.78,0.0,2.0,14.960,20.68,0.0851

In [32]:
df[(df['matchType'] =='solo')&(df['kills'] != 0) & (df['winPlacePerc'])]

,matchId,matchType,Id,groupId,assists,killPlace,kills,matchDuration,boosts,damageDealt,heals,killStreaks,longestKill,walkDistance,winPlacePerc
36,ce9bc89b3ca08c,solo,269c3fc4a26935,3c07be51998e6f,0,24,1,1398,1,100.0,0,1,21.250,1528.0,0.8462
69,e5e181d2da0334,solo,caa1a36afeb7b2,c653cfca3b8b06,0,38,1,2042,1,100.0,0,1,7.667,231.7,0.1573
100,eccc44618c0442,solo,18d002b46b1abc,00a3f236559532,0,7,3,1423,1,236.0,7,1,11.720,1913.0,0.9355
157,c9259d5a2a4f19,solo,50820adcefc866,212fc68772a25a,0,12,2,1801,9,167.4,5,1,82.580,3592.0,0.9222
193,3a3f0763b3a692,solo,67e79b6a3aacc7,1c9169b09317bc,0,30,1,1915,0,79.2,0,1,18.270,664.9,0.4444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446790,cbc3665d093dbc,solo,5af72128847c8b,5692a94aec2f11,0,27,1,1824,2,128.5,3,1,8.584,1468.0,0.7526
4446866,fcb68cbe0723ad,solo,d59c8c30baa84b,51a430f00b03bf,0,26,1,1962,2,109.1,2,1,168.600,2416.0,0.7789
4446889,f7cee5477fe420,solo,5c202630dc0dc2,4e82827eebfd8a,1,25,1,1868,2,200.9,1,1,9.511,2184.0,0.7419
4446929,37bb6013192a8e,solo,a9f6a611553020,c1717785e5a1ba,0,6,3,1418,7,294.1,6,1,89.900,3148.0,0.9694
4446934,836a793f238ea6,solo,5753446d38b5c3,84768a497e690e,0,31,1,1806,0,101.0,1,1,50.870,386.2,0.4301

In [34]:
df_2 = df[(df['matchId']== 'e5e181d2da0334') & (df['killPlace']<50) &(df['winPlacePerc'] < 0.3)]

df_2.sort_values('killPlace',ascending=False)

,matchId,matchType,Id,groupId,assists,killPlace,kills,matchDuration,boosts,damageDealt,heals,killStreaks,longestKill,walkDistance,winPlacePerc
2707410,e5e181d2da0334,solo,8c4a2346d58cae,235931802f1de2,0,39,1,2042,0,233.50,0,1,4.211,260.4,0.1348
69,e5e181d2da0334,solo,caa1a36afeb7b2,c653cfca3b8b06,0,38,1,2042,1,100.00,0,1,7.667,231.7,0.1573
3910469,e5e181d2da0334,solo,6c1107ae225d66,185271842ca8ab,0,37,1,2042,1,149.00,1,1,3.286,370.3,0.2921
2768928,e5e181d2da0334,solo,a45afc9fb43220,fe4bbd76cede70,0,14,2,2042,0,90.36,1,1,9.449,768.4,0.2472

In [35]:
df[(df['matchId']== 'e5e181d2da0334') & (df['killPlace']<10)]

,matchId,matchType,Id,groupId,assists,killPlace,kills,matchDuration,boosts,damageDealt,heals,killStreaks,longestKill,walkDistance,winPlacePerc
630760,e5e181d2da0334,solo,e2347eeaf80100,1b3a5936c2c29d,0,2,8,2042,5,965.3,11,1,186.400,1899.0,0.9551
850162,e5e181d2da0334,solo,ac0cc75669d7ac,e64ed46140a8d0,0,5,4,2042,2,403.0,3,2,22.300,896.9,0.4944
1868170,e5e181d2da0334,solo,1b966c882bd165,5def59d8869d7c,0,7,3,2042,8,370.3,3,1,38.570,3555.0,0.9775
1951096,e5e181d2da0334,solo,e9f621827f8dce,a085caa9575738,0,6,3,2042,6,361.5,2,1,140.100,2520.0,0.9888
2434860,e5e181d2da0334,solo,2f3756c4830c48,281da1ba8ee7a3,1,3,6,2042,10,740.0,9,1,87.970,4693.0,0.9663
2603891,e5e181d2da0334,solo,d801c27b2d32fd,5d44faf5e3833f,0,9,2,2042,1,200.0,1,1,5.056,1887.0,0.8989
2697147,e5e181d2da0334,solo,670d835e216288,f12c259b408634,1,1,10,2042,8,1437.0,4,1,156.300,3009.0,1.0000
3765300,e5e181d2da0334,solo,127f307afb624e,dbdf3eb64e1d44,0,4,4,2042,11,494.2,5,1,31.150,2613.0,0.8539
4284123,e5e181d2da0334,solo,8b7108746f4252,5d2502cd51f12c,0,8,3,2042,0,281.9,0,1,54.590,1310.0,0.5618